default_platform(:android)

platform :android do
 desc "Deploy to Firebase app distribution"
 lane :production do
    gradle(task: "clean")

    version_name = get_version_name(
        gradle_file_path: "./app/build.gradle"
    )

    gradle(
        task: "assembleProductionRelease",
    )

    firebase_app_distribution(
        app: ENV["FIREBASE_APP_PRODUCTION"],
        groups: "testers",
        firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
        release_notes: "Release app",
        apk_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
    )
#   begin
#   firebase_app_distribution(
#    groups: "testers",
#    release_notes: "Fixing bug in features",
#    apk_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
#    firebase_cli_path: "/usr/local/bin/firebase",
#    firebase_cli_token: "1//0gFeihg2NCT2LCgYIARAAGBASNwF-L9IryXi5VWEi83bqBbciPAbaM6L3VZN8FvNqn1RdBr9EMj0AlpS15hBW6uO5_AOhAyE71es",
#    app: "1:1062176853917:android:4b9e61909cc0f4a871e974"
#   )
#   end
 end
end