default_platform(:android)

platform :android do
 desc "Deploy to Firebase app distribution"
 lane :production do
    gradle(task: "clean")

    version_name = get_version_name(
        gradle_file_path: "./app/build.gradle"
    )

    gradle(
        task: "assembleProductionRelease",
    )

    firebase_app_distribution(
        app: ENV["FIREBASE_APP_PRODUCTION"],
        groups: "testers",
        firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
        release_notes: "Release app",
        apk_path: "../build/app/outputs/apk/production/release/app-release-armeabi-v7a.apk",
    )
 end
end